# Generated by Django 5.0.7 on 2024-07-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('native', '0002_register_commune_lat_register_commune_long_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='species',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
