# Generated by Django 5.0.7 on 2024-07-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('native', '0003_register_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='date_1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='date_2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='date_3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='date_4',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
