version: "3"

services:
  api:
    build: ./api
    image: api
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  #react:
  #  build: ./resoliq_ui
  #  image: ui
  #  ports:
  #    - "4200:80"
  #  depends_on:
  #    - api
  #    - postgres
